### ISSUE TITLE
Can not run the tdameriotrade code with error

### ISSUE THREAD

**Issue by baomx888** [areed1192/sigma_coding_youtube#6]
I installed ChromeDriver 81.0.4044.69  and I am using chrome 81.0.4044.92 (Official Build) (64-bit)
I also installed splinter 13.0 and add chromedriver to the environment path.   I can find chromedriver in cmd mode.  

But when I run the code, I got an error
Traceback (most recent call last):
  File "C:/Users/XXX/AppData/Roaming/JetBrains/PyCharm2020.1/scratches/Test.py", line 16, in <module>
    browser = Browser('chrome', **executable_path, headless=False)
  File "C:\Users\XXX\AppData\Roaming\Python\Python36\site-packages\splinter\browser.py", line 90, in Browser
    return get_driver(driver, *args, **kwargs)
  File "C:\Users\XXX\AppData\Roaming\Python\Python36\site-packages\splinter\browser.py", line 68, in get_driver
    raise e
UnboundLocalError: local variable 'e' referenced before assignment

Do you know what I am missing?

**Comment by baomx888** [comment]
solved
